name: Deploy to GitHub Pages and npm

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

permissions:
  contents: write  # Ensure the token has write permissions for contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Directory to deploy

    - name: Publish to npm
      run: |
        retry() {
          local n=1
          local max=1
          local delay=15
          while true; do
            "$@" && break || {
              if [[ $n -lt $max ]]; then
                ((n++))
                echo "Command failed. Attempt $n/$max:"
                sleep $delay;
              else
                echo "The command has failed after $n attempts."
                return 1
              fi
            }
          done
        }
        retry npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}